# Generated by Django 3.2.13 on 2022-05-04 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('stat', models.CharField(choices=[('A', 'Accepted'), ('W', 'Waiting'), ('D', 'Declined')], default='W', max_length=10, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Title')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('status', models.CharField(choices=[('ON', 'Opened'), ('INP', 'In progress'), ('DEL', 'Delayed'), ('OFF', 'Closed'), ('CND', 'Canceled')], default='ON', max_length=3, verbose_name='Статус')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('created_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('details', models.TextField(verbose_name='Детали')),
                ('likes', models.BooleanField(verbose_name='Likes')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
