# Generated by Django 3.2.13 on 2022-05-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pimo', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='stat',
            new_name='status',
        ),
    ]
