# Generated by Django 3.2.13 on 2022-05-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimo', '0004_auto_20220505_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='max_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Лимит'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название'),
        ),
    ]
