# Generated by Django 3.2.13 on 2022-05-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pimo', '0005_auto_20220509_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='post_id',
        ),
    ]
