# Generated by Django 3.2.13 on 2022-05-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pimo', '0006_rename_id_post_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='id',
        ),
    ]
