# Generated by Django 3.2.13 on 2022-05-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_his',
            fields=[
                ('log_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Log_id')),
                ('old_status', models.CharField(max_length=32, verbose_name='Прежний Статус')),
                ('new_status', models.CharField(max_length=32, verbose_name='Новый Статус')),
                ('log_date', models.DateTimeField(auto_now_add=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': ' История предложения',
                'verbose_name_plural': 'Истории предложений',
            },
        ),
        migrations.CreateModel(
            name='Offer_log',
            fields=[
                ('log_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Log_id')),
                ('action', models.CharField(max_length=300, verbose_name='Действия')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Последняя активность')),
                ('last_status', models.CharField(max_length=32, verbose_name='Последний Статус')),
            ],
            options={
                'verbose_name': ' История изменения предложения',
                'verbose_name_plural': 'Истории изменений предложений',
            },
        ),
        migrations.CreateModel(
            name='Order_his',
            fields=[
                ('log_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Log_id')),
                ('old_status', models.CharField(max_length=32, verbose_name='Прежний Статус')),
                ('new_status', models.CharField(max_length=32, verbose_name='Новый Статус')),
                ('log_date', models.DateTimeField(auto_now_add=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': ' История заказа',
                'verbose_name_plural': 'Истории Заказов',
            },
        ),
        migrations.CreateModel(
            name='Order_log',
            fields=[
                ('log_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Log_id')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления')),
                ('last_status', models.CharField(max_length=32, verbose_name='Последний Статус')),
                ('deadline', models.DateTimeField(auto_now_add=True, verbose_name='Deadline')),
            ],
            options={
                'verbose_name': 'История изменения заказа',
                'verbose_name_plural': 'Истории изменений заказов',
            },
        ),
        migrations.CreateModel(
            name='User_backup',
            fields=[
                ('log_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Log_id')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Никнейм')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'User backup',
                'verbose_name_plural': 'User backups',
            },
        ),
        migrations.CreateModel(
            name='User_login_his',
            fields=[
                ('log_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Log_id')),
                ('logged_at', models.DateTimeField(auto_now_add=True, verbose_name='Logged at')),
                ('was_active', models.IntegerField(blank=True, null=True, verbose_name='Был активным')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Никнейм')),
            ],
            options={
                'verbose_name': 'User login history',
                'verbose_name_plural': 'Users login histories',
            },
        ),
        migrations.CreateModel(
            name='User_profile_his',
            fields=[
                ('log_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Log_id')),
                ('old_password', models.CharField(max_length=128, verbose_name='Старый пароль')),
                ('new_password', models.CharField(max_length=128, verbose_name='Новый пароль')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Фамилия')),
                ('old_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Старый email address')),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Новый email address')),
                ('username', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Никнейм')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Log date')),
            ],
            options={
                'verbose_name': 'User profile history',
                'verbose_name_plural': 'Users profile histories',
            },
        ),
    ]
