# Generated by Django 3.2.13 on 2022-05-04 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pimo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_his',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Profile_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
        migrations.AddField(
            model_name='user_login_his',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Log_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
        migrations.AddField(
            model_name='user_backup',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Backup_User_ID', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
        migrations.AddField(
            model_name='order_log',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Log_Order_ID', to='pimo.order', verbose_name='ID Заказа'),
        ),
        migrations.AddField(
            model_name='order_log',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Author_ID', to=settings.AUTH_USER_MODEL, verbose_name='ID автора'),
        ),
        migrations.AddField(
            model_name='order_his',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Histroy_Order_ID', to='pimo.order', verbose_name='ID заказа'),
        ),
        migrations.AddField(
            model_name='offer_log',
            name='offer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Log_Offer_ID', to='pimo.offer', verbose_name='ID предложения'),
        ),
        migrations.AddField(
            model_name='offer_his',
            name='offer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_Offer_ID', to='pimo.offer', verbose_name='ID предложения'),
        ),
    ]
