# Generated by Django 3.2.13 on 2022-05-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20220505_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_log',
            name='user',
            field=models.UUIDField(blank=True, verbose_name='ID автора'),
        ),
    ]
