# Generated by Django 3.2.13 on 2022-05-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_order_log_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_log',
            name='cost',
        ),
    ]
