# Generated by Django 3.2.13 on 2022-05-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_remove_order_log_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_log',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Title'),
        ),
    ]
