# Generated by Django 3.2.13 on 2022-05-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_order_log_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_his',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order_log',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order_log',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_backup',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_login_his',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_profile_his',
            old_name='user',
            new_name='user_id',
        ),
    ]
