# Generated by Django 3.2.13 on 2022-05-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_auto_20220505_0509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer_his',
            options={'verbose_name': ' История изменения предложения', 'verbose_name_plural': 'Истории изменений предложений'},
        ),
        migrations.AlterModelOptions(
            name='offer_log',
            options={'verbose_name': ' История предложения', 'verbose_name_plural': 'Истории предложений'},
        ),
        migrations.AlterModelOptions(
            name='order_his',
            options={'verbose_name': 'История изменения заказа', 'verbose_name_plural': 'Истории изменений заказов'},
        ),
        migrations.AlterModelOptions(
            name='order_log',
            options={'verbose_name': ' История заказа', 'verbose_name_plural': 'Истории Заказов'},
        ),
        migrations.RemoveField(
            model_name='user_profile_his',
            name='deleted_at',
        ),
    ]
