# Generated by Django 3.2.13 on 2022-05-04 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_auto_20220505_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_his',
            name='log_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
