# Generated by Django 3.2.13 on 2022-05-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_auto_20220505_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_log',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Deadline'),
        ),
    ]
